### ISSUE TITLE
Treeview with binding data

### ISSUE THREAD

**Issue by lvchaoin** [Keboo/MaterialDesignInXaml.Examples#6]
Hi Kevin,

Thanks for your examples, it helps a lot !

I am working on project by using the treeviewmenu example,  there's hard code xaml treeviewItem data in the example, once I changed to a binding ObservableCollection data, the Style trigger wouldn't fire.  Could you help to modify the example to adapt the dynamic data ?  I worked whole day on this but haven't found the root cause. Any help would be appreciate.

Regards,

**Comment by Keboo** [comment]
Hi @lvchaoin I have updated the project to include a data bound example. Not perfect but hopefully enough to get you started.
The key here is that because tree view items are virtualized they won't all exist and the previous code was making the assumption that all of the TreeViewItems would be available. To address this, the key to to bind the IsSelected and IsExapanded properties to your view model and control it there. Let me know if you have any questions.
