### ISSUE TITLE
Wouldit be possible to have a branch with .NET 4.6.1 compatiibility ?

### ISSUE THREAD

**Issue by jbogatchenko** [Keboo/MaterialDesignInXaml.Examples#8]
I cannot use the Examples code because we are not using .NET 4.7 yet and are not planning to update for quite a bit. Is it possible to have a clone-able / downloadable branch for Examples with older .NET support ?

**Comment by Keboo** [comment]
@jbogatchenko most (all?) of the examples should compile in .NET 4.6.1. You should be able to change the target framework to 4.6.1 and have it work. Is there a particular example you are having trouble with?

Since these are just example projects, I don't think trying to maintain a second branch just for a different target framework is worth the effort. After .NET 3.0 releases later this year, I may consider doing multi-targeting for the example projects.
